# -*- coding: utf-8 -*-
"""TFLite.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1DOvm1xzGQv5mKy0uOzA6LtqlmJs8GDRG
"""

from google.colab import drive
drive.mount('/content/drive/')

import tensorflow as tf

h5_model_path = "/content/drive/MyDrive/mnist_huruf/model_huruf_cnn.h5"
tflite_model_path = "/content/drive/MyDrive/mnist_huruf/model_huruf_cnn.tflite"

model = tf.keras.models.load_model(h5_model_path)

converter = tf.lite.TFLiteConverter.from_keras_model(model)
tflite_model = converter.convert()

with open(tflite_model_path, "wb") as f:
    f.write(tflite_model)

print(f"Model TFLite telah disimpan di: {tflite_model_path}")

import numpy as np
import tensorflow as tf

# Path ke model TFLite
tflite_model_path = "/content/drive/MyDrive/mnist_huruf/model_huruf_cnn.tflite"

# Buat model TFLite
interpreter = tf.lite.Interpreter(model_path=tflite_model_path)
interpreter.allocate_tensors()

input_details = interpreter.get_input_details()
output_details = interpreter.get_output_details()
print("Input Details:", input_details)
print("Output Details:", output_details)

data_input = np.random.rand(1, 28, 28, 1).astype(np.float32)
interpreter.set_tensor(input_details[0]['index'], data_input)
interpreter.invoke()

output_data = interpreter.get_tensor(output_details[0]['index'])

print("Hasil Prediksi:", output_data)

predicted_class = np.argmax(output_data, axis=1)
print(f"Kelas yang diprediksi: {predicted_class}")